### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by pythcoiner** [slowtec/modbus-core#8]
Hi guys, i would like to know the status of the project?
I plan to use it in several projects (already using [here]() ), both on desktop and embeded, if you still plan to release at some point, i'm ready to help for maintenance, writing examples, etc..., feel free to ping me.

**Comment by flosse** [comment]
@pythcoiner 
I had the project running on an embedded system as a prototype and wanted to adapt the code so that large parts of it could be used in tokio-modbus (see https://github.com/slowtec/tokio-modbus/pull/22 and https://github.com/slowtec/tokio-modbus/issues/16).
However, the embedded project was discontinued, which is why there was no time or money for further development.
If you have the capacity, we can continue the project and of course publish it on crates.io. :smile:

**Comment by pythcoiner** [comment]
Nice! 
What remaining to do in order to have modbus-core ready to publish on crates.io?

**Comment by flosse** [comment]
I actually wanted to clean up the code beforehand, but that will probably have to happen later now :wink: 

Here it is: https://crates.io/crates/modbus-core/0.1.0
